google:
  realm: "llm-chat-wrapper"
  backend_url: "http://localhost:8080/api/v1"
  auth_url: "http://localhost:9082/realms/llm-chat-wrapper/protocol/openid-connect/auth"
  token_url: "http://localhost:9082/realms/llm-chat-wrapper/protocol/openid-connect/token"
  client_id: "desktop-app"
  scope: "openid email profile offline_access"
