spring:
  application:
    name: llm-chat-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    context-path: /api
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: 0FXuDfNIXD6SQKvxPYLufABJjYZKIpRO
    realm: llm-chat-wrapper
    serverUrl: http://localhost:9082