spring:
  devtools:
    add-properties: false
  datasource:
    url: ${PG_URL}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  ai:
    ollama:
      base-url: http://host.docker.internal:11434
logging:
  level:
    org.springframework.boot.autoconfigure.security: WARN
    org.springframework.web: WARN
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans