spring:
  application:
    name: llm-chat-service
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: false
    ollama:
      chat:
        model: llama3.2

server:
  servlet:
    context-path: /api
    
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: CO7Hpc6PqviIDfPQMJU324LpeERoZ2Fx
    realm: llm-chat-wrapper
    serverUrl: http://keycloak:9082