spring:
  devtools:
    add-properties: false
  datasource:
    url: ${PG_URL}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.boot.autoconfigure.security: WARN
    org.springframework.web: WARN
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
server:
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
      - image/svg+xml