services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${PG_DB}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_USER=${PG_USER}'
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      llm_service_network:
        ipv4_address: 172.20.0.100

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    networks:
      llm_service_network:
        ipv4_address: 172.20.0.101

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      llm_service_network:
        ipv4_address: 172.20.0.102

  redis-insight:
    image: 'redis/redisinsight'
    ports:
      - '5540:5540'
    depends_on:
      - redis
    networks:
      llm_service_network:
        ipv4_address: 172.20.0.103
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: start-dev
    restart: always
    depends_on:
      - postgres
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASSWORD}
      KC_DB_URL: ${PG_URL}/keycloak
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      llm_service_network:
        ipv4_address: 172.20.0.104

networks:
  llm_service_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16