version: '3.8'

services:
  postgres:
    restart: always
    image: 'postgres:17.4'
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    volumes:
      - type: bind
        source: ./scripts/init-multiple-dbs.sh
        target: /docker-entrypoint-initdb.d/init-multiple-dbs.sh
        read_only: true
    networks:
      - llm_service_network

  redis:
    restart: always
    image: 'redis:7.4.3'
    networks:
      - llm_service_network

  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:26.2.2
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_SCHEMA: keycloak_schema
      KC_HOSTNAME: keycloak.sezertetik.dev
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_PROXY: edge
      KC_HTTP_ENABLED: 'false'
    networks:
      - llm_service_network

  app:
    restart: always
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      SPRING_PROFILES_ACTIVE: "prod,default"
      PG_DB: ${PG_DB}
      PG_URL: ${PG_URL}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "8080:8081"
    depends_on:
      - postgres
    networks:
      llm_service_network:
        ipv4_address: 172.20.0.105

networks:
  llm_service_network:
